export const ReportData = [

    {
        "labId": 1234,
        "Id": 1,
        "regNo": 5678,
        "patientName": "John Doe",
        "age": 35,
        "gender": "Male",
        "email": "johndoe@example.com",
        "contact": 9876543210,
        "referral": "Dr. Smith",
        "testName": "Blood Test",
        "testDate": "2023-06-30T00:00:00.000Z",
        "history": 1,
        "radiologist": 'Yes',
        "assignedDoctor": "Dr. Johnson",
        "image": "https://example.com/image.jpg",
        "reportType": "X-Ray",
        "status": "Failed",
        "testtype": "ECG",
        "urgent": false,
        "reviewComment": "No abnormal findings",
        "patientHealthParams": {
            "bpSystole": 120,
            "bpDiastole": 80,
            "spo2": 98,
            "pulseRate": 75,
            "height": 175,
            "weight": 70,
            "symptoms": "None"
        }
    },
    {
        "labId": 1234,
        "Id": 2,
        "regNo": 5679,
        "patientName": "John Doe 2",
        "age": 35,
        "gender": "Male",
        "email": "johndoe@example.com",
        "contact": 9876543210,
        "referral": "Dr. Smith",
        "testName": "Blood Test",
        "testDate": "2023-06-30T00:00:00.000Z",
        "history": 1,
        "radiologist": 'No',
        "assignedDoctor": "Dr. Johnson",
        "image": "https://example.com/image.jpg",
        "reportType": "CT-Scan",
        "status": "Pending",
        "testtype": "ECG",
        "urgent": false,
        "reviewComment": "No abnormal findings",
        "patientHealthParams": {
            "bpSystole": 120,
            "bpDiastole": 80,
            "spo2": 98,
            "pulseRate": 75,
            "height": 175,
            "weight": 70,
            "symptoms": "None"
        }
    },
    {
        "labId": 1234,
        "Id": 3,
        "regNo": 5680,
        "patientName": "John Doe 3",
        "age": 35,
        "gender": "Male",
        "email": "johndoe@example.com",
        "contact": 9876543210,
        "referral": "Dr. Smith",
        "testName": "Blood Test",
        "testDate": "2023-06-30T00:00:00.000Z",
        "history": 1,
        "radiologist": 'Yes',
        "assignedDoctor": "Dr. Johnson",
        "image": "https://example.com/image.jpg",
        "reportType": "ECG",
        "status": "Sucess",
        "testtype": "TMG",
        "urgent": false,
        "reviewComment": "No abnormal findings",
        "patientHealthParams": {
            "bpSystole": 120,
            "bpDiastole": 80,
            "spo2": 98,
            "pulseRate": 75,
            "height": 175,
            "weight": 70,
            "symptoms": "None"
        }
    }
]